"""Test script for Level 3 AI Engine validation."""
import requests
import json

# Authenticate
login = requests.post('http://127.0.0.1:8000/auth/login', json={
    'email': 'admin@carepulse.com',
    'password': 'admin123'
})
token = login.json()['access_token']
headers = {'Authorization': f'Bearer {token}'}

def test_patient(patient_id, label):
    print('=' * 70)
    print(label)
    print('=' * 70)
    r = requests.post(f'http://127.0.0.1:8000/ai-insights/generate/{patient_id}', headers=headers)
    d = r.json()
    print(f'Status:        {r.status_code}')
    print(f'Risk Score:    {d["risk_score"]}/100')
    print(f'Risk Level:    {d["risk_level"]}')
    print(f'Trend:         {d["trend_direction"]} ({d["trend_percent"]}%)')
    print(f'Confidence:    {d["confidence"]}%')
    print(f'Generated By:  {d.get("generated_by", "N/A")}')
    print(f'Insight:       {d["insight_text"][:250]}...')
    print(f'Risk Explain:  {str(d.get("risk_explanation", ""))[:250]}...')
    print(f'Recommend:     {d["recommendation"][:250]}...')
    print(f'Mon. Advice:   {str(d.get("monitoring_advice", ""))[:200]}')
    print(f'Tags:          {d.get("tags", "")}')
    print()
    return d

# Patient A: Arthur Mbeki (id=10) — CKD/Renal, critical severity, high wetness, frequent alerts
a = test_patient(10, 'PATIENT A: Arthur Mbeki — End-stage Renal Disease (critical)')

# Patient B: Robert Patel (id=2) — Diabetes, moderate severity, low alerts, stable
b = test_patient(2, 'PATIENT B: Robert Patel — Diabetes Type 2 (moderate)')

# Patient C: Lillian Park (id=9) — UTI, moderate severity, recent diagnosis
c = test_patient(9, 'PATIENT C: Lillian Park — Urinary Tract Infection (moderate)')

# Verify historical insight preservation
print('=' * 70)
print('INSIGHT HISTORY CHECK — Arthur Mbeki (id=10)')
print('=' * 70)
r = requests.get('http://127.0.0.1:8000/ai-insights', headers=headers)
insights = r.json()
arthur_insights = [i for i in insights if i['patient_id'] == 10]
print(f'Total insights for Arthur Mbeki: {len(arthur_insights)}')
for i, ins in enumerate(arthur_insights[:5]):
    gen_by = ins.get('generated_by', 'unknown')
    print(f'  [{i+1}] Score={ins["risk_score"]} Level={ins["risk_level"]} '
          f'By={gen_by} At={ins["generated_at"]}')

print()
print('=' * 70)
print('VALIDATION SUMMARY')
print('=' * 70)
print(f'Patient A risk_level = {a["risk_level"]} (expected: high or critical)  '
      f'{"PASS" if a["risk_level"] in ("high", "critical") else "FAIL"}')
print(f'Patient B risk_level = {b["risk_level"]} (expected: low or moderate)   '
      f'{"PASS" if b["risk_level"] in ("low", "moderate") else "FAIL"}')
print(f'Patient C risk_level = {c["risk_level"]} (expected: moderate or high)  '
      f'{"PASS" if c["risk_level"] in ("moderate", "high") else "FAIL"}')
print(f'All generated_by = rule_engine: '
      f'{"PASS" if all(x.get("generated_by") == "rule_engine" for x in [a,b,c]) else "FAIL"}')
print(f'Arthur insights preserved (>1): '
      f'{"PASS" if len(arthur_insights) > 1 else "FAIL"}')
