"""
CarePulse Backend — models.py
------------------------------
SQLAlchemy ORM models for all four database tables:
    1. Patient
    2. Alert
    3. UrinationEvent
    4. AIInsight

Design notes:
- Primary keys use Integer autoincrement (compatible with both SQLite and MySQL).
- String lengths are explicit (e.g., String(100)) so MySQL can enforce them.
- Enums are stored as VARCHAR strings so values are human-readable in the DB.
- Timestamps use server_default=func.now() so the database engine sets them,
  making migration to MySQL or PostgreSQL straightforward.
- All relationships are defined with back_populates for bidirectional access.
"""

import enum
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


# ================================================================
# ENUMS
# Values stored as strings in the database — readable & portable.
# ================================================================

class WetnessLevel(str, enum.Enum):
    """How saturated the diaper currently is."""
    DRY            = "dry"
    SLIGHTLY_WET   = "slightly_wet"
    MODERATELY_WET = "moderately_wet"
    SATURATED      = "saturated"


class DeviceStatus(str, enum.Enum):
    """Current connectivity state of the IoT sensor."""
    ONLINE      = "online"
    OFFLINE     = "offline"
    MAINTENANCE = "maintenance"


class AlertType(str, enum.Enum):
    """Category of the alert generated by the system."""
    HIGH_WETNESS   = "high_wetness"
    LOW_BATTERY    = "low_battery"
    DEVICE_OFFLINE = "device_offline"
    DIAPER_CHANGED = "diaper_changed"
    CHECK_REQUIRED = "check_required"


class AlertSeverity(str, enum.Enum):
    """Urgency level of an alert."""
    CRITICAL = "critical"
    WARNING  = "warning"
    INFO     = "info"


class RiskLevel(str, enum.Enum):
    """AI-computed patient health risk bucket."""
    LOW      = "low"
    MODERATE = "moderate"
    HIGH     = "high"
    CRITICAL = "critical"


class TrendDirection(str, enum.Enum):
    """Direction of urination frequency trend compared to previous week."""
    UP     = "up"
    DOWN   = "down"
    STABLE = "stable"


# ================================================================
# TABLE 1: patients
# ================================================================

class Patient(Base):
    """
    Represents a patient being monitored by CarePulse.

    Each patient is assigned one IoT diaper sensor (device_id).
    A patient can have many alerts, urination events, and AI insights.
    """

    __tablename__ = "patients"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    # Personal details
    name:      Mapped[str] = mapped_column(String(100), nullable=False)
    age:       Mapped[int] = mapped_column(Integer, nullable=False)

    # Location within the hospital
    ward: Mapped[str] = mapped_column(String(100), nullable=False)
    room: Mapped[str] = mapped_column(String(20),  nullable=False)

    # Medical information
    condition:      Mapped[str]  = mapped_column(String(200), nullable=False)
    caregiver_name: Mapped[str]  = mapped_column(String(100), nullable=False)
    notes:          Mapped[str | None] = mapped_column(Text, nullable=True)

    # IoT device — stored as a string identifier (e.g., "CP-DEV-001")
    # This can be promoted to a FK if a separate devices table is added later.
    device_id: Mapped[str] = mapped_column(String(50), unique=True, nullable=False)

    # Timestamps
    # server_default uses the DB engine clock — works on SQLite, MySQL, and PostgreSQL.
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # ── Relationships ─────────────────────────────────────────
    # One patient → many alerts
    alerts: Mapped[list["Alert"]] = relationship(
        "Alert", back_populates="patient", cascade="all, delete-orphan"
    )

    # One patient → many urination events
    urination_events: Mapped[list["UrinationEvent"]] = relationship(
        "UrinationEvent", back_populates="patient", cascade="all, delete-orphan"
    )

    # One patient → many AI insight records
    ai_insights: Mapped[list["AIInsight"]] = relationship(
        "AIInsight", back_populates="patient", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Patient id={self.id} name={self.name!r}>"


# ================================================================
# TABLE 2: alerts
# ================================================================

class Alert(Base):
    """
    An alert generated when a patient's sensor reading crosses
    a configured threshold (e.g., wetness > 75%, battery < 25%).

    Alerts are created automatically by the monitoring logic and
    resolved manually by caregivers via the dashboard.
    """

    __tablename__ = "alerts"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    # Foreign key to the patient this alert belongs to.
    # ON DELETE CASCADE: if a patient is deleted, their alerts are deleted too.
    patient_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("patients.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Alert classification
    alert_type: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="Enum: high_wetness | low_battery | device_offline | diaper_changed | check_required"
    )
    severity: Mapped[str] = mapped_column(
        String(20), nullable=False,
        comment="Enum: critical | warning | info"
    )

    # Human-readable description sent to the caregiver
    message: Mapped[str] = mapped_column(Text, nullable=False)

    # Resolution tracking
    resolved:    Mapped[bool]          = mapped_column(Boolean, default=False, nullable=False)
    resolved_at: Mapped[datetime|None] = mapped_column(DateTime, nullable=True)

    # Timestamp when the alert was first triggered
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False, index=True
    )

    # ── Relationship back to Patient ──────────────────────────
    patient: Mapped["Patient"] = relationship("Patient", back_populates="alerts")

    def __repr__(self) -> str:
        return f"<Alert id={self.id} type={self.alert_type!r} severity={self.severity!r}>"


# ================================================================
# TABLE 3: urination_events
# ================================================================

class UrinationEvent(Base):
    """
    A single sensor reading captured from the IoT smart diaper.

    Each record represents one snapshot:
    - Current wetness level and percentage
    - Current device battery and status

    These records are the raw time-series data used to:
    - Drive the real-time dashboard wetness trend chart
    - Calculate daily urination frequency
    - Feed the AI pattern analysis engine
    """

    __tablename__ = "urination_events"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    # Foreign key to the patient this reading belongs to
    patient_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("patients.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Wetness measurement from the capacitive sensor (0–100 %)
    wetness_percent: Mapped[float] = mapped_column(Float, nullable=False)

    # Categorised wetness label computed from wetness_percent
    wetness_level: Mapped[str] = mapped_column(
        String(30), nullable=False,
        comment="Enum: dry | slightly_wet | moderately_wet | saturated"
    )

    # Device telemetry recorded with this reading
    battery_percent: Mapped[float]  = mapped_column(Float, nullable=False)
    device_status:   Mapped[str]    = mapped_column(
        String(20), nullable=False,
        comment="Enum: online | offline | maintenance"
    )

    # When the sensor reading was captured (not when it was stored in the DB)
    recorded_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, index=True)

    # When the record was inserted into the database
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )

    # ── Relationship back to Patient ──────────────────────────
    patient: Mapped["Patient"] = relationship("Patient", back_populates="urination_events")

    def __repr__(self) -> str:
        return (
            f"<UrinationEvent id={self.id} "
            f"patient_id={self.patient_id} "
            f"wetness={self.wetness_percent}%>"
        )


# ================================================================
# TABLE 4: ai_insights
# ================================================================

class AIInsight(Base):
    """
    An AI-generated health insight record for a patient.

    Insights are periodically computed (e.g., once per hour) by
    analysing the patient's urination_events time-series data.
    Each record captures a full snapshot of the analysis output.

    Fields:
    - risk_score:        0–100 numerical risk score
    - risk_level:        Bucketed risk label (low / moderate / high / critical)
    - trend_direction:   Whether urination frequency is going up, down, or stable
    - trend_percent:     % change vs. previous week
    - insight_text:      Detailed AI-generated clinical observation
    - recommendation:    Suggested caregiver action
    - confidence:        Model confidence in this prediction (0–100 %)
    - tags:              Comma-separated clinical category tags
                         (e.g., "Renal,Nocturia,Urgent")
    """

    __tablename__ = "ai_insights"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    # Foreign key to the patient this insight is about
    patient_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("patients.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Risk quantification
    risk_score: Mapped[int] = mapped_column(
        Integer, nullable=False,
        comment="Numerical risk score from 0 (no risk) to 100 (critical)"
    )
    risk_level: Mapped[str] = mapped_column(
        String(20), nullable=False,
        comment="Enum: low | moderate | high | critical"
    )

    # Trend analysis
    trend_direction: Mapped[str] = mapped_column(
        String(10), nullable=False,
        comment="Enum: up | down | stable — compared to previous 7 days"
    )
    trend_percent: Mapped[float] = mapped_column(
        Float, nullable=False,
        comment="Percentage change in urination frequency vs. previous week"
    )

    # AI-generated text content
    insight_text:   Mapped[str] = mapped_column(Text, nullable=False)
    recommendation: Mapped[str] = mapped_column(Text, nullable=False)

    # Model metadata
    confidence: Mapped[float] = mapped_column(
        Float, nullable=False,
        comment="AI model confidence in this insight (0–100 %)"
    )

    # Comma-separated clinical tags (e.g., "Renal,Nocturia,Urgent").
    # Simple format avoids a separate join table for Phase 1.
    # Can be normalised into a tags table in a later phase.
    tags: Mapped[str | None] = mapped_column(
        String(500), nullable=True,
        comment="Comma-separated clinical tags, e.g. 'Renal,Nocturia,Urgent'"
    )

    # When the AI model generated this insight (may differ from DB insert time)
    generated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, index=True)

    # When the record was inserted into the database
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )

    # ── Relationship back to Patient ──────────────────────────
    patient: Mapped["Patient"] = relationship("Patient", back_populates="ai_insights")

    def __repr__(self) -> str:
        return (
            f"<AIInsight id={self.id} "
            f"patient_id={self.patient_id} "
            f"risk={self.risk_score} risk_level={self.risk_level!r}>"
        )
